run:
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - "pkg/internal/unsafes"
    - "vendor$"
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*(.|_)gen\\.go$"
    - ".*\\.deepcopy\\.go$"
  modules-download-mode: readonly

linters-settings:
  dupl:
    threshold: 400
  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/zchee/kt
  golint:
    min-confidence: 0.3
  govet:
    enable:
      -  asmdecl
      -  assign
      -  atomic
      -  atomicalign
      -  bools
      -  buildssa
      -  buildtag
      -  cgocall
      -  composite
      -  copylock
      -  ctrlflow
      -  deepequalerrors
      -  errorsas
      -  findcall
      -  httpresponse
      -  inspect
      -  loopclosure
      -  lostcancel
      -  nilfunc
      -  nilness
      -  pkgfact
      -  printf
      -  shift
      -  sortslice
      -  stdmethods
      -  structtag
      -  tests
      -  unmarshal
      -  unreachable
      -  unsafeptr
      -  unusedresult
    disable:
      -  shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: false

linters:
  # disabled:
  #   - funlen
  #   - gochecknoglobals
  #   - gochecknoinits
  #   - gocyclo
  #   - godox
  #   - gomnd
  #   - gosec
  #   - lll
  #   - nakedret
  #   - scopelint
  #   - unused
  #   - wsl
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - megacheck
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-use-default: true
  exclude-rules:
    - path: pkg/cmd/cmd.go
      text: "func `\\(\\*kt\\).Run` is high"
      linters:
        - gocognit

    - path: pkg/manager/manager.go
      text: "Error return value of `kubescheme.AddToScheme` is not checked"
      linters:
        - errcheck

    - path: pkg/options/options.go
      text: "struct of size \\d* bytes could be of size \\d* bytes"
      linters:
        - maligned

    - path: pkg/pool/goroutine.go
      linters:
        - unparam

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
