version: 2.1

orbs:
  golang: cci-orb/golang@volatile    # https://circleci.com/orbs/registry/orb/cci-orb/golang
  codecov: codecov/codecov@volatile  # https://circleci.com/orbs/registry/orb/codecov/codecov

jobs:
  test:
    executor:
      name: golang/linux
      version: "1.15-buster"
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/zchee/kt
    resource_class: large
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run test
          command: |
            make coverage/ci
      - codecov/upload:
          file: "/tmp/artifacts/coverage.out"
          when: on_success
          flags: linux
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results

  lint:
    executor:
      name: golang/linux
      version: "1.15-buster"
    working_directory: /go/src/github.com/zchee/kt
    resource_class: large
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
