# For Kubernetes 1.15.x
---
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:  # https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
- |
  # kube-apiserver
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "CSIInlineVolume=true,CustomResourceDefaulting=true,LocalStorageCapacityIsolationFSQuotaMonitoring=true,NonPreemptingPriority=true,RemainingItemCount=true,RequestManagement=true,ServiceLoadBalancerFinalizer=true,VolumePVCDataSource=true,WatchBookmark=true"
- |
  # kubelet
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "CSIInlineVolume=true,CustomResourceDefaulting=true,LocalStorageCapacityIsolationFSQuotaMonitoring=true,NonPreemptingPriority=true,RemainingItemCount=true,RequestManagement=true,ServiceLoadBalancerFinalizer=true,VolumePVCDataSource=true,WatchBookmark=true"

# networking:
#   ipFamily: ipv6  # ipv4, ipv6

nodes:  # three node (two workers) cluster config
- role: control-plane
- role: worker
  extraPortMappings:
  - listenAddress: "0.0.0.0"  # Optional, defaults: "0.0.0.0"
    protocol: tcp # Optional, available values are tcp or udp. defaults: tcp
- role: worker
  extraPortMappings:
  - listenAddress: "0.0.0.0"  # Optional, defaults: "0.0.0.0"
    protocol: tcp # Optional, available values are tcp or udp. defaults: tcp
